### ISSUE TITLE
Lando pull doesn't recognize ACLI

### ISSUE THREAD

**Issue by samuelshumake** [lando/acquia#57]
After initializing lando on my acquia site, I went to run `lando pull`. I choose the code/database/files and it looks like it begins to pull but immediately flags this error:

`/helpers/acquia-pull.sh: line 90: /usr/local/bin/acli: No such file or directory`

I then downloaded the Acquia CLI using the [documentation here](https://docs.acquia.com/acquia-cli/install/). I ran lando rebuild and received error messages about 
`PHP Fatal error:  Uncaught Error: Failed opening required '/app/vendor/composer/../../docroot/core/includes/bootstrap.inc'` 

but the rebuild still pushes through. After pulling again, I receive the same error about there not being a file or directory in acli.

This is what my lando.yml file looks like (removed the ah_application_uuid and ah_site_group):

```
recipe: acquia
config:
  webroot: ./docroot
  acli_version: latest
  php: '8.1'
services:
  appserver:
    type: 'php:8.1'
```
