### ISSUE TITLE
Acquia is not working with xdebug

### ISSUE THREAD

**Issue by dantetwc** [lando/acquia#6]
Hi All and thanks for developing lando. It is a great tool for devs!
I am trying to debug with xdebug with acquia recipe. 
According to doc [here](https://docs.lando.dev/config/acquia.html), it should support xdebug option.
However, it doesnot work for me and after some digging, it seems the receipe disable xdebug no matter how [code](https://github.com/lando/cli/blob/main/integrations/lando-acquia/recipes/acquia/builder.js#L32)

Is there anyway to enable xdebug for acquia recipe?

Thanks again.

**Comment by cdubz** [comment]
There was a notification of a question from someone on this ticket just before it was moved. Not sure if the author removed it or something weird happened with the timing of the issue move but the question was essentially, "is there any workaround for this bug?". Here's a small snippet of the relevant config in my `.lando.yml` to get xdebug working:

```
[...]
services:
  appserver:
    build_as_root_internal:
      - docker-php-ext-enable xdebug
    overrides:
      environment:
        XDEBUG_MODE: 'debug'
[...]
```
